<?php
// api/user/register_device.php
// Receives a device token from the client app and registers it for push notifications.
header('Content-Type: application/json');

require_once '../db_connect.php';

$input = json_decode(file_get_contents('php://input'), true);

// --- Validation ---
$userId = isset($input['user_id']) ? (int)$input['user_id'] : 0;
// A unique ID generated by the device/OS to identify this specific app installation
$deviceId = isset($input['device_id']) ? trim($input['device_id']) : '';
// The push token (e.g., from Firebase Cloud Messaging or Apple Push Notification Service)
$pushToken = isset($input['fcm_token']) ? trim($input['fcm_token']) : ''; // Assuming FCM for now
$deviceName = isset($input['device_name']) ? trim($input['device_name']) : 'Unnamed Device';

if ($userId <= 0 || empty($deviceId) || empty($pushToken)) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'user_id, device_id, and fcm_token are required.']);
    exit();
}

try {
    // Use INSERT ... ON DUPLICATE KEY UPDATE to handle both new devices and token refreshes.
    // This requires a UNIQUE key on (user_id, device_id) in the database, which we already have.
    $sql = "
        INSERT INTO user_devices (user_id, device_id, fcm_token, device_name, is_active, last_active)
        VALUES (?, ?, ?, ?, 1, NOW())
        ON DUPLICATE KEY UPDATE
            fcm_token = VALUES(fcm_token),
            device_name = VALUES(device_name),
            is_active = 1,
            last_active = NOW()
    ";

    $stmt = $pdo->prepare($sql);
    $stmt->execute([$userId, $deviceId, $pushToken, $deviceName]);

    http_response_code(200);
    echo json_encode(['success' => true, 'message' => 'Device registered successfully.']);

} catch (PDOException $e) {
    http_response_code(500);
    error_log("Device Registration Error for user_id {$userId}: " . $e->getMessage());
    echo json_encode(['success' => false, 'message' => 'Database update failed during device registration.']);
}
?>